version: 2
updates:
  # Enable version updates for Swift
  - package-ecosystem: "swift"
    # Look for `Package.wift` and `Package.resolved` files in the `root` directory
    directory: "./"
    schedule:
      interval: "weekly"

  # Enable version updates for github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

